title         : Vyshnav Gangadharan
description   : >- # this means to ignore newlines until "baseurl:"
  A UI/UX designer who loves Coding, Illustrating & creating 3D stuff
baseurl       : "" # the subpath of your site, e.g. /blog
url           : "" # the base hostname & protocol for your site, e.g. http://example.com


### Author Info ###
author:
  name              : Vyshnav Gangadharan
  image             : /assets/avatar.png
  twitter           : vyshnav_xyz
  figma             : vyshnav
  dribbble          : vyshnav_
  github            : Vyshnav2255
  linkedin          : vyshnav-gangadharan
#  goodreads         : vyshnav
  buy me a coffee   : vyshnav


### Analytics ###
analytics:
  enabled: true
  google:
    tracking_id: G-GD7E2GW8RY

sass:
    style: compressed

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - vendor